### Rota para pegar todos os pedidos
GET http://localhost:3000/

### fechando a requisição


### Pegar um único produto pelo ID

GET http://localhost:3000/pedido/5
Content-Type: application/json

### fechando requisição



### Rota criando o produto
POST http://localhost:3000/pedido
Content-Type: application/json

{
    "cliente": "João Gomes", 
    "medicamentos": "Dipirona",
    "quantidade": "2",
    "valor_total": "10.00",
    "status": "2",
    "forma_pagamento": "Dinheiro"   
}
### fechando requisição


### PUT - Editar Produto
PUT http://localhost:3000/pedido/6
Content-Type: application/json

{
    "novoCliente": "João Gomes", 
    "novoMedicamentos": "ASS",
    "novoQuantidade": "5",
    "novoValor_total": "100.00",
    "novoStatus": "3",
    "novoForma_pagamento": "Cartão"    
}
### fechando requisição



### DELETE - Deletar produto
DELETE http://localhost:3000/pedido/5
Content-Type: application/json
### fechando requisição


### Deletar todos produtos
DELETE http://localhost:3000/pedido
Content-Type: application/json
### fechando requisição

